author: rami.io
author_url: http://pretix.eu
github_url: https://github.com/pretix
copyright: '© 2019 [rami.io](http://rami.io)'

module: pretixSCAN
module_version: 1.0a

theme: fullwidth

custom_categories:
  - name: TicketValidator
    children:
    - TicketValidator
    - OnlineTicketValidator
    - OfflineTicketValidator

  - name: ConfigStore
    children:
    - ConfigStore
    - ConfigStoreValue
    - InMemoryConfigStore
    - DefaultsConfigStore

  - name: Data Storage & Sync
    children:
    - DataStore
    - InMemoryDataStore
    - FMDBDataStore
    - SyncManager
    - APIClient

  - name: Server Communication
    children:
    - PagedList
    - DeviceInitializationResponseError
    - DeviceInitializationRequest
    - DeviceInitializationResponse
    - QueuedRedemptionRequest

  - name: Models
    children:
    - Model
    - Event
    - SubEvent
    - CheckInList
    - CheckIn
    - OrderPosition
    - Handshake
    - RedemptionRequest
    - RedemptionResponse
    - Locale
    - CheckInListStatus
    - Item
    - ItemAddon
    - ItemBundle
    - ItemCategory
    - ItemVariation
    - Order
    - Identifier
    - Money
    - MultiLingualString
