author: rami.io
author_url: http://pretix.eu
github_url: https://github.com/pretix
copyright: '© 2019 [rami.io](http://rami.io)'

swift_version: 4.2.1

module: PretixScan
module_version: 1.0a

custom_categories:
  - name: TicketValidator
    children:
    - TicketValidator
    - OnlineTicketValidator

  - name: ConfigStore
    children:
    - ConfigStore
    - InMemoryConfigStore

  - name: Models
    children:
    - Event
    - CheckInList
    - CheckIn
    - OrderPosition
    - Handshake
    - DeviceInitializationRequest
    - DeviceInitializationResponse
    - RedemptionRequest
    - RedemptionResponse
    
  - name: API Client
    children:
    - APIClient

  - name: Meta Models
    children: 
    - PagedList
    - MultiLingualString
